version: '3.8'

services:
  dep-scanner:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Persistent cache storage
      - ./data:/app/data
      # Mount local projects for scanning (optional)
      - ./scan-projects:/app/scan-projects:ro
    environment:
      # API Configuration
      - API_HOST=0.0.0.0
      - API_PORT=8000
      
      # Cache Configuration
      - CACHE_TTL_HOURS=24
      - CACHE_CLEANUP_INTERVAL_HOURS=6
      
      # OSV.dev API Configuration  
      - OSV_API_URL=https://api.osv.dev
      - OSV_RATE_LIMIT_CALLS=100
      - OSV_RATE_LIMIT_PERIOD=60
      
      # Database path (within container)
      - CACHE_DB_PATH=/app/data/osv_cache.db
      
    restart: unless-stopped
    container_name: dep-scanner-backend
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=10)"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s
      
  # Optional: Nginx proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - dep-scanner
    restart: unless-stopped
    container_name: dep-scanner-nginx
    profiles:
      - production

volumes:
  data:
    driver: local