"""Test configuration and fixtures for pytest"""
import pytest
import asyncio
from pathlib import Path
from typing import Dict
from unittest.mock import Mock

from backend.core.models import ScanOptions, Dep, Vuln, SeverityLevel, Report, JobStatus


@pytest.fixture
def event_loop():
    """Create an instance of the default event loop for the test session."""
    loop = asyncio.get_event_loop_policy().new_event_loop()
    yield loop
    loop.close()


@pytest.fixture
def sample_scan_options() -> ScanOptions:
    """Sample scan options for testing"""
    return ScanOptions(
        include_dev_dependencies=True,
        ignore_severities=[]
    )


@pytest.fixture
def sample_python_dep() -> Dep:
    """Sample Python dependency"""
    return Dep(
        name="requests",
        version="2.25.1",
        ecosystem="PyPI",
        path=["requests"],
        is_direct=True,
        is_dev=False
    )


@pytest.fixture
def sample_js_dep() -> Dep:
    """Sample JavaScript dependency"""
    return Dep(
        name="lodash",
        version="4.17.19",
        ecosystem="npm",
        path=["lodash"],
        is_direct=True,
        is_dev=False
    )


@pytest.fixture
def sample_vulnerability() -> Vuln:
    """Sample vulnerability"""
    return Vuln(
        package="requests",
        version="2.25.1",
        ecosystem="PyPI",
        vulnerability_id="PYSEC-2022-43012",
        severity=SeverityLevel.HIGH,
        cvss_score=7.5,
        cve_ids=["CVE-2022-48147"],
        summary="Requests library vulnerable to SSRF",
        details="The Requests library is vulnerable to SSRF attacks when...",
        advisory_url="https://osv.dev/vulnerability/PYSEC-2022-43012",
        fixed_range=">=2.31.0"
    )


@pytest.fixture
def sample_report(sample_python_dep, sample_vulnerability) -> Report:
    """Sample report with one vulnerability"""
    return Report(
        job_id="test-job-123",
        status=JobStatus.COMPLETED,
        total_dependencies=1,
        vulnerable_count=1,
        vulnerable_packages=[sample_vulnerability],
        dependencies=[sample_python_dep],
        suppressed_count=0,
        meta={"ecosystems": ["Python"], "scan_options": {}}
    )


@pytest.fixture
def mock_progress_callback() -> Mock:
    """Mock progress callback for testing"""
    return Mock()


@pytest.fixture
def sample_package_json() -> str:
    """Sample package.json content"""
    return '''{
  "name": "test-project",
  "version": "1.0.0",
  "dependencies": {
    "lodash": "^4.17.19",
    "axios": "^0.21.0"
  },
  "devDependencies": {
    "jest": "^26.0.0"
  }
}'''


@pytest.fixture
def sample_requirements_txt() -> str:
    """Sample requirements.txt content"""
    return '''requests==2.25.1
urllib3==1.26.5
certifi==2021.5.30'''


@pytest.fixture
def sample_pyproject_toml() -> str:
    """Sample pyproject.toml content"""
    return '''[tool.poetry]
name = "test-project"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.25.1"
pydantic = "^2.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.0.0"
black = "^22.0.0"
'''


@pytest.fixture
def temp_test_dir(tmp_path) -> Path:
    """Create a temporary directory for testing"""
    return tmp_path


@pytest.fixture
def sample_yarn_lock() -> str:
    """Sample yarn.lock content for testing"""
    return '''# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@babel/code-frame@^7.0.0":
  version "7.22.13"
  resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.22.13.tgz#e3c1c099402598483b7a8c46a721d1038803755e"
  integrity sha512-XktuhWlJ5g+3TJXc5upd9Ks1HutSArik6jf2eAjYFyIOf4ej3RN+184cZbzDvbPnuTJIUhPKKJE3cIsYTiAT3w==
  dependencies:
    "@babel/highlight" "^7.22.13"

"@babel/highlight@^7.22.13":
  version "7.22.20"
  resolved "https://registry.yarnpkg.com/@babel/highlight/-/highlight-7.22.20.tgz#4ca92b71d80554b01427815e06f2df965b9c1f54"
  integrity sha512-dkdMCN3py0+ksCgYmGG8jKeGA/8Tk+gJwSYYlFGxG5lmhfKNoAy004YpLxpS1W2J8m/EK2Ew+yOs9pVRwO89mg==
  dependencies:
    "@babel/helper-validator-identifier" "^7.22.20"
    chalk "^2.4.2"
    js-tokens "^4.0.0"

"@babel/helper-validator-identifier@^7.22.20":
  version "7.22.20"
  resolved "https://registry.yarnpkg.com/@babel/helper-validator-identifier/-/helper-validator-identifier-7.22.20.tgz#c4ae002c61d2879e724581d96665583dbc1dc0e0"
  integrity sha512-Y4OZ+ytlatR8AI+8KZfKuL5urKp7qey08ha31L8b3BwewJAoJamTzyvxPR/5D+KkdJCGPq/+8TukHBlY10FX9A==

chalk@^2.4.2:
  version "2.4.2"
  resolved "https://registry.yarnpkg.com/chalk/-/chalk-2.4.2.tgz#cd42541677a54333cf541a49108c1432b44c9424"
  integrity sha512-Mti+f9lpJNcwF4tWV8/OrTTtF1gZi+f8FqlyAdouralcFWFQWF2+NgCHShjkCb+IFBLq9buZwE1xckQU4peSuQ==
  dependencies:
    ansi-styles "^3.2.1"
    escape-string-regexp "^1.0.5"
    supports-color "^5.3.0"

ansi-styles@^3.2.1:
  version "3.2.1"
  resolved "https://registry.yarnpkg.com/ansi-styles/-/ansi-styles-3.2.1.tgz#41fbb20243e50b12be0f04b8dedbf07520ce841d"
  integrity sha512-VT0ZI6kZRdTh8YyJw3SMbYm/u+NqfsAxEpWO0Pf9sq8/e94WxxOpPKx9FR1FlyCtOVDNOQ+8ntlqFxiRc+r5qA==
  dependencies:
    color-convert "^1.9.0"

js-tokens@^4.0.0:
  version "4.0.0"
  resolved "https://registry.yarnpkg.com/js-tokens/-/js-tokens-4.0.0.tgz#19203fb59991df98e3a287050d4647cdeaf32499"
  integrity sha512-RdJUflcE3cUzKiMqQgsCu06FPu9UdIJO0beYbPhHN4k6apgJtifcoCtT9bcxOpYBtpD2kCM6Sbzg4CausW/PKQ==

lodash@^4.17.15:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#679591c564c3bffaae8454cf0b3df370c3d6911c"
  integrity sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg=='''


@pytest.fixture
def sample_manifest_files(sample_package_json, sample_requirements_txt) -> Dict[str, str]:
    """Sample manifest files dictionary"""
    return {
        "package.json": sample_package_json,
        "requirements.txt": sample_requirements_txt
    }