version: '3.8'

services:
  dep-scanner:
    build:
      context: ../..
      dockerfile: Dockerfile.aws
    ports:
      - "8000:8000"
    volumes:
      # Persistent cache and logs
      - dep_scanner_data:/app/data
      - dep_scanner_logs:/app/logs
    environment:
      # API Configuration
      - API_HOST=0.0.0.0
      - API_PORT=8000
      
      # Cache Configuration
      - CACHE_TTL_HOURS=24
      - CACHE_CLEANUP_INTERVAL_HOURS=6
      - CACHE_DB_PATH=/app/data/osv_cache.db
      
      # OSV.dev API Configuration  
      - OSV_API_URL=https://api.osv.dev
      - OSV_RATE_LIMIT_CALLS=100
      - OSV_RATE_LIMIT_PERIOD=60
      
      # Production Settings
      - LOG_LEVEL=INFO
      - MAX_WORKERS=4
      - KEEPALIVE_TIMEOUT=65
      
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
      
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  dep_scanner_data:
    driver: local
  dep_scanner_logs:
    driver: local